name: 'REST API Fuzz Testing (RAFT) Action'
description: 'Fuzz your REST APIs using RESTler, ZAP and more!'
inputs:
  mode:
    description: 'Setting the mode to azure will deploy against your azure RAFT deployment'
    required: false
    default: local
  arguments :
    description: 'RAFT CLI arguments'
    required: true
  logDirectory:
    description: 'Copy logs to this directory'
    required: false
    default: '.raft'
  raftDefaults:
    description: 'RAFT defaults.json contents'
    required: false
  secret:
    description: 'Service Principal secret for RAFT deployment'
    required: false

branding:
  icon: 'check-circle'  
  color: 'gray-dark'

runs:
  using: "composite"
  steps:           
    - run: pip3 install -r ${{github.action_path}}/requirements.txt
      shell: bash
    - run: ${{ github.action_path}}/runRaft.sh "${{ inputs.mode }}" "${{ inputs.arguments }}" "${{ inputs.raftDefaults }}" "${{ inputs.secret }}" "${{ github.action_path }}"
      shell: bash
    - run: ${{ github.action_path }}/copyLogFiles.sh "${{ inputs.mode }}" "${{ inputs.logDirectory }}" "${{ github.action_path }}" "{{ github.workspace }}"
      shell: bash